version: '3'
services:
  npm-sum-service:
    image: "${DOCKERHUB_USERNAME}/sum-service"
    container_name: sum-service
    restart: always
    ports:
     - "3001:3000"
    networks:
     - "npm-microservices"
  npm-subtraction-service:
    image: "${DOCKERHUB_USERNAME}/subtraction-service"
    container_name: subtraction-service
    restart: always
    ports:
     - "3002:3000"
    networks:
     - "npm-microservices"
  npm-multiplication-service:
    image: "${DOCKERHUB_USERNAME}/multiplication-service"
    container_name: multiplication-service
    restart: always
    ports:
     - "3003:3000"
    networks:
     - "npm-microservices"
  npm-division-service:
    image: "${DOCKERHUB_USERNAME}/division-service"
    container_name: division-service
    restart: always
    ports:
     - "3004:3000"
    networks:
     - "npm-microservices"
  ui-service:
    image: "${DOCKERHUB_USERNAME}/ui-service"
    container_name: ui-service
    environment:
      - HOST_IP=${HOST_IP}
    restart: always
    ports:
     - "3000:3000"
    networks:
     - "npm-microservices"
networks:
  npm-microservices: